language: node_js
node_js:
- lts/*
cache:
  yarn: true
branches:
  only:
  - master
  - develop
  - "/^release.*/"
script:
  - yarn build
deploy:
  provider: gae
  keyfile: "./deploy-secret.json"
  project: cytoid
  on:
    repo: Cytoid/api.cytoid.io
    branch: master
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_0403ac132abb_key -iv $encrypted_0403ac132abb_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
