runtime: nodejs10
instance_class: F1
service: api
automatic_scaling:
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.9
  max_instances: 1
  min_instances: 0
  max_concurrent_requests: 100
  max_idle_instances: 1
  min_idle_instances: 0
  min_pending_latency: 10ms
  max_pending_latency: 50ms
