GET {{host}}/users
Accept: application/json
Authorization: Bearer {{jwt}}

###



POST {{host}}/users
Accept: application/json
Content-Type: application/json; charset=utf-8

{
"email": "test@cytoid.io",
  "uid": "cytoid",
"name": "okCytoidTesting",
  "password": "testingtesting"
}
###
