POST {{host}}/users
Accept: application/json
Content-Type: application/json; charset=utf-8

{
"email": "example@examgpolfge.com",
  "uid": "adfasdf",
"name": "death",
  "password": "dfadsfasdfasdf",
  "irrelevent": "d"
}
###
